/**
 * 遊戲定義清單 — 前後台共用
 * 每個遊戲對應 GameSettings global 中的開關欄位名稱 & 設定 group 名稱
 */
export interface GameDef {
  id: string
  slug: string
  enabledKey: string // gameList.xxxEnabled
  settingsKey: string // group name in GameSettings
  name: string
  icon: string
  color: string // tailwind gradient
  description: string
  category: 'luck' | 'social' | 'challenge' | 'creative'
  categoryLabel: string
}

export const GAME_DEFS: GameDef[] = [
  {
    id: 'daily-checkin',
    slug: 'daily-checkin',
    enabledKey: 'dailyCheckinEnabled',
    settingsKey: 'dailyCheckin',
    name: '每日簽到',
    icon: '📅',
    color: 'from-amber-400 to-orange-500',
    description: '每天簽到賺點數，連續七天有大獎！',
    category: 'luck',
    categoryLabel: '每日獎勵',
  },
  {
    id: 'spin-wheel',
    slug: 'spin-wheel',
    enabledKey: 'spinWheelEnabled',
    settingsKey: 'spinWheel',
    name: '幸運轉盤',
    icon: '🎡',
    color: 'from-pink-400 to-rose-500',
    description: '轉動命運之輪，贏取超值獎品！',
    category: 'luck',
    categoryLabel: '幸運抽獎',
  },
  {
    id: 'scratch-card',
    slug: 'scratch-card',
    enabledKey: 'scratchCardEnabled',
    settingsKey: 'scratchCard',
    name: '刮刮樂',
    icon: '🎫',
    color: 'from-emerald-400 to-teal-500',
    description: '刮開驚喜，幸運就在指尖！',
    category: 'luck',
    categoryLabel: '幸運抽獎',
  },
  {
    id: 'movie-lottery',
    slug: 'movie-lottery',
    enabledKey: 'movieLotteryEnabled',
    settingsKey: 'movieLottery',
    name: '電影票抽獎',
    icon: '🎬',
    color: 'from-violet-400 to-purple-500',
    description: '用點數抽威秀電影票！',
    category: 'luck',
    categoryLabel: '幸運抽獎',
  },
  {
    id: 'fashion-challenge',
    slug: 'fashion-challenge',
    enabledKey: 'fashionChallengeEnabled',
    settingsKey: 'fashionChallenge',
    name: '璀璨穿搭挑戰',
    icon: '✨',
    color: 'from-gold-400 to-amber-600',
    description: '60秒混搭穿搭，AI即時評分！',
    category: 'challenge',
    categoryLabel: '穿搭挑戰',
  },
  {
    id: 'card-battle',
    slug: 'card-battle',
    enabledKey: 'cardBattleEnabled',
    settingsKey: 'cardBattle',
    name: '抽卡片比大小',
    icon: '🃏',
    color: 'from-blue-400 to-indigo-500',
    description: '邀請好友抽卡對戰，比大小贏點數！',
    category: 'social',
    categoryLabel: '好友互動',
  },
  {
    id: 'style-pk',
    slug: 'style-pk',
    enabledKey: 'stylePKEnabled',
    settingsKey: 'stylePK',
    name: '穿搭 PK 對戰',
    icon: '⚔️',
    color: 'from-red-400 to-rose-600',
    description: '上傳穿搭照，與玩家PK投票！',
    category: 'challenge',
    categoryLabel: '穿搭挑戰',
  },
  {
    id: 'style-relay',
    slug: 'style-relay',
    enabledKey: 'styleRelayEnabled',
    settingsKey: 'styleRelay',
    name: '穿搭接龍',
    icon: '🔗',
    color: 'from-cyan-400 to-blue-500',
    description: '延續風格元素，接力創造穿搭故事！',
    category: 'creative',
    categoryLabel: '創意穿搭',
  },
  {
    id: 'weekly-challenge',
    slug: 'weekly-challenge',
    enabledKey: 'weeklyChallengeEnabled',
    settingsKey: 'weeklyChallenge',
    name: '每週風格挑戰賽',
    icon: '🏆',
    color: 'from-yellow-400 to-amber-500',
    description: '每週不同主題，爭奪穿搭冠軍！',
    category: 'challenge',
    categoryLabel: '穿搭挑戰',
  },
  {
    id: 'co-create',
    slug: 'co-create',
    enabledKey: 'coCreateEnabled',
    settingsKey: 'coCreate',
    name: '好友共創穿搭',
    icon: '👯',
    color: 'from-fuchsia-400 to-pink-500',
    description: '邀請好友一起搭配，共同創作造型！',
    category: 'social',
    categoryLabel: '好友互動',
  },
  {
    id: 'wish-pool',
    slug: 'wish-pool',
    enabledKey: 'wishPoolEnabled',
    settingsKey: 'wishPool',
    name: '穿搭許願池',
    icon: '🌟',
    color: 'from-sky-400 to-indigo-400',
    description: '許下穿搭願望，讓達人幫你圓夢！',
    category: 'creative',
    categoryLabel: '創意穿搭',
  },
  {
    id: 'blind-box',
    slug: 'blind-box',
    enabledKey: 'blindBoxEnabled',
    settingsKey: 'blindBox',
    name: '穿搭盲盒互贈',
    icon: '🎁',
    color: 'from-lime-400 to-green-500',
    description: '隨機搭配盲盒送給好友，拆箱驚喜！',
    category: 'social',
    categoryLabel: '好友互動',
  },
  {
    id: 'queen-vote',
    slug: 'queen-vote',
    enabledKey: 'queenVoteEnabled',
    settingsKey: 'queenVote',
    name: '女王投票大賽',
    icon: '👑',
    color: 'from-gold-400 to-yellow-500',
    description: '上傳最美穿搭，爭奪時尚女王寶座！',
    category: 'challenge',
    categoryLabel: '穿搭挑戰',
  },
  {
    id: 'team-style',
    slug: 'team-style',
    enabledKey: 'teamStyleEnabled',
    settingsKey: 'teamStyle',
    name: '團體穿搭房',
    icon: '🏠',
    color: 'from-orange-400 to-red-400',
    description: '開房邀請好友，穿搭競賽贏大獎！',
    category: 'social',
    categoryLabel: '好友互動',
  },
]

export const GAME_CATEGORIES = [
  { id: 'luck', label: '幸運抽獎', icon: '🍀' },
  { id: 'challenge', label: '穿搭挑戰', icon: '🔥' },
  { id: 'social', label: '好友互動', icon: '💕' },
  { id: 'creative', label: '創意穿搭', icon: '🎨' },
] as const
